### PR TITLE
Added Quick Sort

### PR DESCRIPTION
**Pull request by Girish345**
https://drive.google.com/drive/folders/1NW2JVa1JETSN3NXtVT3UAi64WUkj7u-U

Added drive link video is to large

### CODE REVIEW

**Comment by PrathameshTheurkar** [comment]
@Girish345 

> https://drive.google.com/drive/folders/1NW2JVa1JETSN3NXtVT3UAi64WUkj7u-U
> 
> Added drive link video is to large

I have requested for the access , give me the access of the drive

**Comment by Girish345** [comment]
#3 I have added quick sort functionality and added drive link of quick sort also

**Comment by PrathameshTheurkar** [comment]
> #3 I have added quick sort functionality and added drive link of quick sort also

A sorting algo should sort the given array but your algo is not doing it so check ur code once , until and unless u solve this issue your further PR of merge sort and stop button functionlaity can't be accepted  as ur quick sort algo is not sorting the array .

**Comment by Girish345** [comment]
ok till then you can accept merge it is different issue

**Comment by PrathameshTheurkar** [comment]
> ok till then you can accept merge it is different issue

But in that merge sort PR there is three files changed and one of that is Quick  sort and if I accept ur PR then quick sort will also get merged so raise a new PR through different branch in which only merge sort algo is added .

**Comment by Girish345** [comment]
I have raise PR through different branch

**Comment by Girish345** [comment]
for every issue

**Pull request closed without merging**
