### PR TITLE
Added time complexities and pseduo code section for the algorithms

### PR DESCRIPTION
**Pull request by IbraheemHaseeb7**
This PR addresses the issue #4 

image

the design is also responsive

### CODE REVIEW

**Comment by PrathameshTheurkar** [comment]
https://github.com/pccoe-acm-hacktoberfest-2023/Sorting_Visualizer/assets/109230625/f9173254-b08d-4991-9dc3-8aea35840375

@IbraheemHaseeb7 well done bro but there is one slight problem as you  can see in this video , until  I click on the sort button it is not showing the algo and time complexity . The solution for this issue should be in the way that when I click on the bubble sort button it should immediately show the algo and time complexity , I need not to click on the sort button for it  .

**Comment by IbraheemHaseeb7** [comment]
Sure @PrathameshTheurkar give me sometime....let me fix it

**Comment by IbraheemHaseeb7** [comment]
@PrathameshTheurkar its fixed now you can check it......i have also opened a new pull request that has sorted out the merge conflits so you don't have to resolve them....you can close this one and merge that if you want

its id is #16

**Comment by PrathameshTheurkar** [comment]
> d now you can check it......i have also opened a new pull request that has sorted out the merge conflits so you don't have to resolve them....you can close this one and merge that if you want
> 
> its id is #16

good one bro

**Comment by IbraheemHaseeb7** [comment]
I am sorry but can you tell me why is it not merged?

**Comment by PrathameshTheurkar** [comment]
Actually this is only for the our clg students , actually this is our clg event so we can't allow outsiders to send the PR  and I was unaware that u were not from our clg .

**Comment by IbraheemHaseeb7** [comment]
oh okay no worries....can you at least add this into your read me or something? 😅

**Comment by PrathameshTheurkar** [comment]
> oh okay no worries....can you at least add this into your read me or something? 😅

yes yes  sure !!

**Pull request closed without merging**
