### PR TITLE
Stop functionality

### PR DESCRIPTION
**Pull request by Girish345**
https://github.com/pccoe-acm-hacktoberfest-2023/Sorting_Visualizer/assets/96805555/4b6b5bae-4959-46cd-8288-98d2b7d88572

Added stopping functionality with video

### CODE REVIEW

**Comment by PrathameshTheurkar** [comment]
@Girish345 stop functionality is working good but the quick sort algo is not working first try to solve it first so that I can merge this PR

**Comment by Girish345** [comment]
#2 stop functionality

**Comment by Girish345** [comment]
I have checked bro wait i will add video

**Comment by Girish345** [comment]
https://deploy-preview-10--acm-sorting-visualizer.netlify.app/ 
check this

**Comment by PrathameshTheurkar** [comment]
https://github.com/pccoe-acm-hacktoberfest-2023/Sorting_Visualizer/assets/109230625/5282b68b-76af-4cee-bb36-7ce470afd65f

this is ur netlify preview bro it is not sorting the array just changing the color of each bar

**Comment by Girish345** [comment]
got it bro I will work on that I will resolve error by today

**Comment by PrathameshTheurkar** [comment]
> t bro I will work on that I will resolve er

ok

**Pull request closed without merging**
