### PR TITLE
Merge sort

### PR DESCRIPTION
**Pull request by Girish345**
https://github.com/pccoe-acm-hacktoberfest-2023/Sorting_Visualizer/assets/96805555/e79eeed9-9dd3-499e-8864-199fac6551c4

Added code with video

### CODE REVIEW

**Comment by PrathameshTheurkar** [comment]
@Girish345 Quick Sort Algo is not working , check it once .

**Comment by Girish345** [comment]
I have shared video it is working

**Comment by PrathameshTheurkar** [comment]
@Girish345 and also mention the issue no. while raising the PR  here so that your pull request can be displayed in that particular issue .

**Comment by PrathameshTheurkar** [comment]
> I have shared video it is working

that video u send was of the merge sort algo and that is working but the quick sort is not  working .

**Comment by PrathameshTheurkar** [comment]
just check once

**Comment by Girish345** [comment]
#1 This is the PR of merge sort, 
I have raised the another PR of quick sort before the PR of merge sort, so would you check that PR first

**Comment by PrathameshTheurkar** [comment]
I am closing this PR for now bro just make sure that u raise a PR for one issue at a time  and mention the issue no .  and  make PR through different branches for each issue so that your PRs are not conflicted .

**Pull request closed without merging**
